Projeto/Controllers/AutoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Livros.Data;
using Livros.Models;

namespace Livros.Controllers
{
    public class AutoresController : Controller
    {
        private readonly Context _context;

        public AutoresController(Context context)
        {
            _context = context;
        }

        // GET: Autores
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autores.OrderBy(a => a.NomeAutor).ToListAsync());
        }

        // GET: Autores/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoresModel = await _context.Autores.SingleOrDefaultAsync(m => m.IdAutor == id);
            if (autoresModel == null)
            {
                return NotFound();
            }

            return View(autoresModel);
        }

        // GET: Autores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Autores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AutoresModel autoresModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(autoresModel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("Erro", "Nao foi possivel inserir os dados.");
            }

            return View(autoresModel);
        }

        // GET: Autores/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoresModel = await _context.Autores.SingleOrDefaultAsync(a => a.IdAutor == id);
            if (autoresModel == null)
            {
                return NotFound();
            }
            return View(autoresModel);
        }

        // POST: Autores/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id,  AutoresModel autoresModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(autoresModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutoresModelExists(autoresModel.IdAutor))
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(autoresModel);
        }

        // GET: Autores/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var autoresModel = await _context.Autores
                .SingleOrDefaultAsync(m => m.IdAutor == id);
            if (autoresModel == null)
            {
                return NotFound();
            }

            
            var fkTrue = await _context.LivrosAutoresEditoras.AnyAsync(d => d.fk_AutorID == id);

            if (fkTrue)
            {
                TempData["erro"] = $"Não podemos apaga o Autor:{autoresModel.NomeAutor.ToUpper()} porque estar relacionado a {_context.LivrosAutoresEditoras.Count(d => d.fk_AutorID == id)} Autores(s)";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(autoresModel);
            }

        }

        // POST: Autores/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var autoresModel = await _context.Autores.FindAsync(id);
            if (autoresModel != null)
            {
                _context.Autores.Remove(autoresModel);
            }
            
            await _context.SaveChangesAsync();
            TempData["Message"] = $"Livro {autoresModel?.NomeAutor.ToUpper()} foi removido";

            return RedirectToAction(nameof(Index));
        }

        private bool AutoresModelExists(int? id)
        {
          return _context.Autores.Any(e => e.IdAutor == id);
        }
    }
}

Projeto/Controllers/EditorasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Livros.Data;
using Livros.Models;

namespace Livros.Controllers
{
    public class EditorasController : Controller
    {
        private readonly Context _context;

        public EditorasController(Context context)
        {
            _context = context;
        }

        // GET: Editoras
        public async Task<IActionResult> Index()
        {
            return View(await _context.Editoras.OrderBy(e => e.NomeEditora).ToListAsync());
        }

        // GET: Editoras/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editorasModel = await _context.Editoras.SingleOrDefaultAsync(m => m.IdEditora == id);
            if (editorasModel == null)
            {
                return NotFound();
            }

            return View(editorasModel);
        }

        // GET: Editoras/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Editoras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EditorasModel editorasModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(editorasModel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception)
            {

                ModelState.AddModelError("Erro", "Nao foi possivel inserir os dados.");
            }

            return View(editorasModel);
        }

        // GET: Editoras/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editorasModel = await _context.Editoras.SingleOrDefaultAsync(e => e.IdEditora == id);
            if (editorasModel == null)
            {
                return NotFound();
            }
            return View(editorasModel);
        }

        // POST: Editoras/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, EditorasModel editorasModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(editorasModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EditorasModelExists(editorasModel.IdEditora))
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(editorasModel);
        }

        // GET: Editoras/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editorasModel = await _context.Editoras
                .SingleOrDefaultAsync(m => m.IdEditora == id);
            if (editorasModel == null)
            {
                return NotFound();
            }

            var fkTrue = await _context.LivrosAutoresEditoras.AnyAsync(d => d.fk_EditoraID == id);

            if (fkTrue)
            {
                TempData["erro"] = $"Não podemos apaga o Editora:{editorasModel.NomeEditora.ToUpper()} porque estar relacionado a {_context.LivrosAutoresEditoras.Count(d => d.fk_EditoraID == id)} Editora(s)";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(editorasModel);

            }

        }

        // POST: Editoras/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (_context.Editoras == null)
            {
                return Problem("Entity set 'Context.Editoras'  is null.");
            }
            var editorasModel = await _context.Editoras.FindAsync(id);
            if (editorasModel != null)
            {
                _context.Editoras.Remove(editorasModel);
            }
            
            await _context.SaveChangesAsync();
            TempData["Message"] = $"Editora {editorasModel?.NomeEditora.ToUpper()} foi removido";

            return RedirectToAction(nameof(Index));
        }

        private bool EditorasModelExists(int? id)
        {
          return _context.Editoras.Any(e => e.IdEditora == id);
        }
    }
}

Projeto/Controllers/LivrosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Livros.Data;
using Livros.Models;

namespace Livros.Controllers
{
    public class LivrosController : Controller
    {
        private readonly Context _context;

        public LivrosController(Context context)
        {
            _context = context;
        }

        // GET: Livros
        public async Task<IActionResult> Index()
        {
            return View(await _context.Livros.OrderBy(c => c.TituloLivro).ToListAsync());
                         
        }

        // GET: Livros/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livrosModel = await _context.Livros.SingleOrDefaultAsync(m => m.IdLivro == id);

            if (livrosModel == null)
            {
                return NotFound();
            }

            return View(livrosModel);
        }

        // GET: Livros/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Livros/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LivrosModel livrosModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(livrosModel);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {

                ModelState.AddModelError("Erro", "Nao foi possivel inserir os dados.");
            }

            return View(livrosModel);
        }

        // GET: Livros/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livrosModel = await _context.Livros.SingleOrDefaultAsync(m => m.IdLivro == id);
            if (livrosModel == null)
            {
                return NotFound();
            }
            return View(livrosModel);
        }

        // POST: Livros/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, LivrosModel livrosModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livrosModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivrosModelExists(livrosModel.IdLivro))
                    {
                        return NotFound();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livrosModel);
        }

        // GET: Livros/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livrosModel = await _context.Livros
                .SingleOrDefaultAsync(m => m.IdLivro == id);
            if (livrosModel == null)
            {
                return NotFound();
            }

            //com o id da instuicao pesquina no departamento se tem alguma fk carrega
            var fkTrue = await _context.LivrosAutoresEditoras.AnyAsync(d => d.fk_LivrosID == id);

            if (fkTrue)
            {
                TempData["erro"] = $"Não podemos apaga o Livro:{livrosModel.TituloLivro.ToUpper()} porque estar relacionado a {_context.LivrosAutoresEditoras.Count(d => d.fk_LivrosID == id)} Autores(s)";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(livrosModel);

            }

        }

        // POST: Livros/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var livrosModel = await _context.Livros.SingleOrDefaultAsync(m => m.IdLivro == id);
            if (livrosModel != null)
            {
                _context.Livros.Remove(livrosModel);
            }
            await _context.SaveChangesAsync();

            TempData["Message"] = $"Livro {livrosModel?.TituloLivro.ToUpper()} foi removido";

            return RedirectToAction(nameof(Index));
        }

        private bool LivrosModelExists(int? id)
        {
          return _context.Livros.Any(e => e.IdLivro == id);
        }
    }
}

Projeto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Livros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Livros.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header>

        <div class="container-fluid px-0">
            <nav class="navbar navbar-expand-sm navbar-dark bg-black py-0 px-0">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    Editora Educação
                </a>
                <span class="v-line"></span>
                <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" asp-area="" asp-controller="Livros" asp-action="Index">Livros</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Editoras" asp-action="Index">Editoras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="LivroAutorEditora" asp-action="Index">Relacione tudo!</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

@*<footer class="border-top footer text-muted h-25">
        <div class="container">
            &copy; 2023 - $1$ Livros - #1# <a asp-area="" asp-controller="LivroAutorEditora" asp-action="Index">Livros</a>
        </div>
    </footer>*@
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Fernando Balieiro Ferreira
  </div>
  <!-- Copyright -->
</footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" />
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css"></script>


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />

    <script src="https://code.jquery.com/jquery-3.7.0.slim.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>